version: '3.8'

services:
 
  # basic
  shell:
    build:
      context: .
    working_dir: /app
    entrypoint: bash
    stdin_open: true
    tty: true
    volumes:
    - ./src:/app/src
    - ./data:/app/data
    - ./conf:/app/conf
