wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1648427208
    t:
      1:
      - 1
      3:
      - 1
      - 16
      - 24
      4: 3.8.10
      5: 0.12.11
      8:
      - 5
batch_size:
  desc: null
  value: 64
dropout:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
epochs:
  desc: null
  value: 100
h:
  desc: null
  value: 500
hidden_layers:
  desc: null
  value: 2
i:
  desc: null
  value: 14
log_interval:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.00013981961408994042
patience:
  desc: null
  value: 30
save:
  desc: null
  value: true
seed:
  desc: null
  value: 0
test_batch_size:
  desc: null
  value: 1000
validation:
  desc: null
  value: false
